# Generated by Django 4.1.4 on 2023-07-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_projects_thumbnail_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('meta', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('thumbnail_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(default='uncategorized', max_length=255)),
                ('slug', models.CharField(max_length=100)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='category',
            field=models.CharField(default='uncategorized', max_length=350),
        ),
    ]
